In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn import metrics

In [2]:
# reading training set
# this training set had duplicate
whole_training = pd.read_csv('training.csv')

#drop Category of the subject that's null
whole_training.dropna(inplace = True)

#msk = np.random.rand(len(whole_training)) < 0.8
#train = whole_training[msk]
#test = whole_training[~msk]

#data cleaning
whole_training["source"].replace('Google Play',0,inplace=True)
whole_training["source"].replace('App Store',1,inplace=True)
#whole_training.drop(['review_description', 'review_date',"roberta_comp'"], axis=1)
whole_training = whole_training[["source","rating","vader_neg","vader_neu","vader_pos","vader_compound", "roberta_neg","roberta_neu","roberta_pos","roberta_comp","category"]]

In [3]:
whole_training

,source,rating,vader_neg,vader_neu,vader_pos,vader_compound,roberta_neg,roberta_neu,roberta_pos,roberta_comp,category
0,0,4,0.000,1.000,0.000,0.0000,0.022908,0.840722,0.136370,0.113461,3
1,0,1,0.000,1.000,0.000,0.0000,0.871913,0.117503,0.010584,-0.861329,4
2,0,5,0.000,0.000,1.000,0.6249,0.008338,0.083822,0.907840,0.899503,1
3,0,3,0.000,0.769,0.231,0.3400,0.232840,0.733593,0.033567,-0.199273,0
4,1,5,0.096,0.704,0.200,0.4215,0.268035,0.347671,0.384294,0.116260,5
...,...,...,...,...,...,...,...,...,...,...,...
212,0,3,0.000,0.816,0.184,0.5423,0.141384,0.747885,0.110731,-0.030652,5
213,0,5,0.000,1.000,0.000,0.0000,0.164881,0.624972,0.210146,0.045265,0
214,0,5,0.000,0.517,0.483,0.5768,0.002883,0.020585,0.976532,0.973650,0
215,0,4,0.105,0.670,0.225,0.3612,0.055968,0.301281,0.642752,0.586784,9
216,1,5,0.000,0.926,0.074,0.0900,0.003862,0.059915,0.936224,0.932362,0

In [4]:
#Splitting the data into independent and dependent variables
X = whole_training.iloc[:,0:10].values
y = whole_training.iloc[:,10].values
print('The independent features set: ')
print(X[:10,:])
print('The dependent variable: ')
print(y[:10])

The independent features set:
[[ 0.00000000e+00  4.00000000e+00  0.00000000e+00  1.00000000e+00
   0.00000000e+00  0.00000000e+00  2.29084160e-02  8.40721846e-01
   1.36369720e-01  1.13461301e-01]
 [ 0.00000000e+00  1.00000000e+00  0.00000000e+00  1.00000000e+00
   0.00000000e+00  0.00000000e+00  8.71913016e-01  1.17503226e-01
   1.05837260e-02 -8.61329317e-01]
 [ 0.00000000e+00  5.00000000e+00  0.00000000e+00  0.00000000e+00
   1.00000000e+00  6.24900000e-01  8.33755000e-03  8.38222650e-02
   9.07840252e-01  8.99502695e-01]
 [ 0.00000000e+00  3.00000000e+00  0.00000000e+00  7.69000000e-01
   2.31000000e-01  3.40000000e-01  2.32839882e-01  7.33593464e-01
   3.35666760e-02 -1.99273199e-01]
 [ 1.00000000e+00  5.00000000e+00  9.60000000e-02  7.04000000e-01
   2.00000000e-01  4.21500000e-01  2.68034786e-01  3.47670794e-01
   3.84294391e-01  1.16259605e-01]
 [ 0.00000000e+00  2.00000000e+00  0.00000000e+00  7.92000000e-01
   2.08000000e-01  6.12400000e-01  2.89056420e-01  6.34765327e-01
   7.61782450e-02 -2.12878168e-01]
 [ 0.00000000e+00  4.00000000e+00  0.00000000e+00  8.43000000e-01
   1.57000000e-01  7.72000000e-02  9.35475469e-01  6.17966390e-02
   2.72785200e-03 -9.32747602e-01]
 [ 0.00000000e+00  1.00000000e+00  3.18000000e-01  6.82000000e-01
   0.00000000e+00 -2.18300000e-01  9.34855580e-01  5.99782760e-02
   5.16605300e-03 -9.29689527e-01]
 [ 0.00000000e+00  5.00000000e+00  0.00000000e+00  4.84000000e-01
   5.16000000e-01  4.92700000e-01  2.40386200e-03  1.66911820e-02
   9.80904937e-01  9.78501081e-01]
 [ 0.00000000e+00  5.00000000e+00  0.00000000e+00  5.08000000e-01
   4.92000000e-01  4.40400000e-01  7.43195410e-02  2.91869968e-01
   6.33810520e-01  5.59490979e-01]]
The dependent variable:
['3' '4' '1' '0' '5' '5' '6' '0' '0' '0']

In [11]:
y

array(['3', '4', '1', '0', '5', '5', '6', '0', '0', '0', '1', '0', '0',
       '0', '1', '0', '0', '1', '5', '0', '0', '5', '0', '0', '0', '5',
       '3', '4', '0', '13', '0', '12', '3', '0', '0', '4', '13', '0', '0',
       '0', '4', '5', '13', '0', '13', '0', '6', '0', '0', '0', '0', '2',
       '9', '4', '5', '0', '0', '5', '0', '6', '2', '0', '2', '0', '1',
       '0', '0', '13', '0', '0', '0', '13', '13', '0', '0', '0', '0', '5',
       '3', '5', '6', '0', '0', '0', '3', '9', '4', '13', '2', '7', '0',
       '0', '5', '0', '1', '0', '0', '13', '0', '0', '0', '0', '2', '9',
       '0', '0', '0', '0', '0', '0', '9', '13', '0', '3', '3', '0', '0',
       '0', '0', '0', '1', '4', '0', '8', '3', '0', '3', '0', '1', '13',
       '0', '6', '1', '4', '0', '6', '5', '0', '4', '2', '6', '0', '4',
       '13', '2', '5', '13', '0', '13', '1', '5', '0', '0', '10', '5',
       '5', '9', '13', '5', '0', '0', '5', '7', '0', '0', '2', '0', '4',
       '6', '0', '0', '3', '0', '0', '0', '5', '0', '3', '5', '13', '0',
       '0', '1', '7', '13', '0', '3', '0', '1', '0', '0', '13', '0', '0',
       '0', '3', '5', '0', '0', '9', '0'], dtype=object)

In [6]:
# Feature Scaling
# use oob score, so no training data set
scaler = StandardScaler()
X = scaler.fit_transform(X)

In [7]:
# Fitting Random Forest Classification to the Training set
classifier = RandomForestClassifier(oob_score=True, n_estimators = 10, criterion = 'entropy', random_state = 42)
classifier.fit(X, y)

print(classifier.oob_score_)

0.472636815920398

In [10]:
# random forest
y_pred = classifier.predict(X)
#print(y_pred)
#print(y)
correct = (np.array(y_pred) == np.array(y))
accuracy = correct.sum() / correct.size
print(f"accuracy is {accuracy}\n")
print(pd.crosstab(y, y_pred, rownames=['Actual Category'], colnames=['Predicted Category']))

accuracy is 0.900497512437811

Predicted Category   0  1  10  13  2   3  4   5  6  7  9
Actual Category
0                   98  0   0   0  0   0  0   0  0  0  0
1                    1  8   0   2  0   0  1   0  0  0  0
10                   0  0   1   0  0   0  0   0  0  0  0
12                   0  0   0   0  0   1  0   0  0  0  0
13                   0  0   0  18  0   0  0   0  0  0  0
2                    0  0   0   0  7   0  0   1  0  0  0
3                    0  0   0   0  0  12  0   1  0  0  0
4                    0  1   0   0  0   1  8   1  0  0  0
5                    0  1   0   0  0   3  0  17  0  0  0
6                    0  0   0   0  0   0  0   0  8  0  0
7                    0  1   0   0  1   0  0   0  0  1  0
8                    0  0   0   1  0   0  0   0  0  0  0
9                    0  0   0   0  0   1  1   1  0  0  3

In [44]:
# reading training set
# this training set had duplicate
df = pd.read_csv('SENTIMENT SCORE v5.csv')


#drop Category of the subject that's null
df.fillna(0,inplace = True)

#data cleaning
df["source"].replace('Google Play',0,inplace=True)
df["source"].replace('App Store',1,inplace=True)
df = df[["source","rating","vader_neg","vader_neu","vader_pos","vader_compound", "roberta_neg","roberta_neu","roberta_pos","roberta_comp"]]

In [45]:
X_actual = df.iloc[:,0:10].values
# Feature Scaling
# use oob score, so no training data set
scaler = StandardScaler()
X_actual = scaler.fit_transform(X_actual)
y_pred_result = classifier.predict(X_actual)

In [46]:
y_pred_result

array(['2', '0', '0', ..., '2', '0', '0'], dtype=object)

In [47]:
# reading training set
# this training set had duplicate
df_original = pd.read_csv('SENTIMENT SCORE v5.csv')

#drop Category of the subject that's null
df_original.fillna(0,inplace = True)

In [50]:
df_original

,index1,source,review_description,rating,review_date,vader_neg,vader_neu,vader_pos,vader_compound,roberta_neg,roberta_neu,roberta_pos,roberta_comp,prediction
0,1,Google Play,"At this time it doesn't allow new accounts, on...",1,2023/7/5 22:53,0.143,0.857,0.000,-0.1695,0.372755,0.580568,0.046677,-0.326079,2
1,2,Google Play,Incredible!,5,2023/7/5 22:53,0.000,1.000,0.000,0.0000,0.700000,0.200000,0.887891,0.187891,0
2,3,Google Play,First review of this app ðŸ˜ðŸ’€ðŸ¤ðŸ»,5,2023/7/5 22:54,0.000,1.000,0.000,0.0000,0.017739,0.391545,0.590716,0.572978,0
3,4,Google Play,First one to rate this app,5,2023/7/5 22:56,0.000,1.000,0.000,0.0000,0.006916,0.280264,0.712820,0.705904,5
4,5,Google Play,this gotta be one of the apps of all time,5,2023/7/5 22:56,0.000,1.000,0.000,0.0000,0.026084,0.274946,0.698970,0.672885,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32905,32906,Google Play,"twitter but without the fun, features, or real...",1,2023/7/25 09:32,0.308,0.692,0.000,-0.5504,0.000000,0.000000,0.000000,0.000000,2
32906,32907,Google Play,"I just noticed that sorting the ""earliest and ...",3,2023/7/25 09:32,0.091,0.909,0.000,-0.7275,0.000000,0.000000,0.000000,0.000000,2
32907,32908,Google Play,Idk man seems and looks like an app from the 90's,1,2023/7/25 09:35,0.109,0.698,0.194,0.2732,0.000000,0.000000,0.000000,0.000000,2
32908,32909,Google Play,Super app,5,2023/7/25 09:37,0.000,0.204,0.796,0.5994,0.000000,0.000000,0.000000,0.000000,0
32909,32910,Google Play,Nithinlucky,5,2023/7/25 09:42,0.000,1.000,0.000,0.0000,0.000000,0.000000,0.000000,0.000000,0

In [49]:
df_original["prediction"] = y_pred_result

In [51]:
df_original.to_csv("prediction_results.csv")